version: '3.9'

services:
  kysely_codegen_adminer:
    container_name: kysely_codegen_adminer
    image: adminer
    ports:
      - 8081:8080
    restart: always
  kysely_codegen_libsql:
    container_name: kysely_codegen_libsql
    image: ghcr.io/libsql/sqld:latest
    ports:
      - 8080:8080
    restart: always
  kysely_codegen_mysql:
    container_name: kysely_codegen_mysql
    environment:
      - MYSQL_DATABASE=qwe
      - MYSQL_PASSWORD=qwe
      - MYSQL_ROOT_PASSWORD=qwe
      - MYSQL_USER=qwe
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
  kysely_codegen_postgres:
    container_name: kysely_codegen_postgres
    environment:
      - POSTGRES_DB=qwe
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_USER=qwe
    image: postgres:latest
    ports:
      - 5433:5432
    restart: always
